name: Deploying the calculator app to GH pages

on:
    push:
        branches:
            - core/deploying
            - master

permissions:
    contents: read
    pages: write
    id-token: write

jobs: 
    linter:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install environment
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci
            
            - name: Running linter
              run: npm run lint

            - name: Running compiler
              run: npm run compile

            - name: Generate file css
              run: npx tailwindcss -i assets/style/style.css -o dist/style/output.css --watch
    
    build_and_testing:
        needs: linter
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install environment
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci

            - name: Testing the app
              run: npm run test
    
    deploy:
        needs: build_and_testing
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install environment
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci
            
            - name: Configure GH pages
              uses: actions/configure-pages@v3 
            
            - name: Uploading GH pages artifact
              uses: actions/upload-pages-artifact@v2
              with: 
                path: './dist/'

            - name: Deploy to GH pages
              id: deployment
              uses: actions/deploy-pages@v2