name: Deploying the calculator app to GH pages

on:
    push:
        branches:
            - core/deploying
            - master
    
jobs: 
    linter:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install environment
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci
            
            - name: Running linter
              run: npm run lint
    
    testing:
        needs: linter
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - run: npm ci

            - name: Testing the app
              run: npm run test
    
    build_and_deploy:
        needs: testing

        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            contents: read
            pages: write
            id-token: write

        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with: 
                node-version: 20
                cache: 'npm'
            
            - run: npm ci

            - name: Running compiler
              run: npm run build

            - name: Generate file css
              run: npm run compile_style
            
            - name: Configure GH pages
              uses: actions/configure-pages@v3 
          
            - run: cp index.html ./dist/

            - name: Upload favicon
              run: cp assets/images/favicon-32x32.png ./dist/
            
            - name: Upload fonts
              run: cp assets/fonts/League_Spartan/LeagueSpartan-Regular.ttf ./dist/

            - uses: actions/upload-pages-artifact@v2
              with: 
                path: ./dist/
                if-no-files-found: error

            - name: Deploy to GH pages
              id: deployment
              uses: actions/deploy-pages@v1